bundlesPath: ./bundle-configs

bundleConfigFormat: yaml

tasks:

  mocha:
    testsDir:
    compile: true

  minify:
    cssBuildPath: ./public/css/
    jsBuildPath: ./public/js/
    htmlBuildPath: ./public/
    template:
      templatePartial: |
        App.setTemplate('');
      compressWhitespace: true
      templateTypeKeys:
        - mustache
        - handlebars
        # @todo remove ejs templates
        - ejs

  jshint:
    jshintrc: ./.jshintrc
    ignoredFiles:
      - jquery.js
      - require.js
      - require-text.js
      - modernizr.js

  # Build Task
  build:

    # This is a global lint flag that is used if there is a lint task specified for a section
    lintBeforeBuild: true

  # Deploy Task
  deploy: ./bundle-wrangler-configs/deploy-config.yaml
