bundlesPath: ./bundle-configs

scriptRenderer: ejs

bundleConfigFormat: yaml

tasks:

  concat:
    header: |
      /*!
       * Company Name http://www.company-website.com
       * <%= bundle.options.name %>.<%= fileExt %> <%= bundle.options.version %>
       * <%= fileHash %>
       */
    cssBuildPath: ./public/css/
    jsBuildPath: ./public/js/
    htmlBuildPath: ./public/

  minify:
    header: |
      /*! Company Name http://www.company-website.com <%= bundle.options.name %>.<%= fileExt %> <%= bundle.options.version %> <%= fileHash %> */
    cssBuildPath: ./public/css/
    jsBuildPath: ./public/js/
    htmlBuildPath: ./public/

  # Build Task
  build:

    # This is a global lint flag that is used if there is a lint task specified for a section
    lintBeforeBuild: true

  # Deploy Task
  deploy:

    # Files to be deployed (merged with bundle level definition;  e.g., bundleFile.deploy.files)
    files: []

    # Global deploy artifacts flag (used if no `deployArtifact` field is found for a section in this config
    deployArtifacts: true

    # Should files be linted before deploy
    lintBeforeDeploy: false

    allowedImageTypes: /\.(?:jpg|png|gif|tiff)$/i

    allowedVideoTypes: /\.(?:flv|mpeg|mpg|mp3|mp4|ogg|vorbis)$/i

#    allowedFontTypes: /\.(?:flv|mpeg|mpg|mp3|mp4|ogg|vorbis)$/i

    hosts:

      # Hostname to develop for
      gulpw.elycruz.com:

        # Servers where user can develop for host key (in this case host key is `gulpw.elycruz.com`)
        servers: # slots
          - devslot1.gulpw-sample.somedomain.com
          - devslot2.gulpw-sample.somedomain.com
          - devslot3.gulpw-sample.somedomain.com

        # all sites represent the same website just different instances of the website
        sites: # instances
          - web1
          - web2
          - web3

        # directories for deploying file types to the website instance chosen
        paths: # dir
          font: public/media/fonts/
          html: public/media/html/
          video: public/media/videos/
          image: public/media/images/
          javascript: public/js/
          stylesheet: public/css/
