bundlesPath: ./bundle-configs

scriptRenderer: ejs

bundleConfigFormat: yaml

tasks:

  mocha:
    testsDir:
    compile: true

  concat:
    header: |
      /*!
       * Company Name http://www.company-website.com
       * <%= bundle.options.name %>.<%= fileExt %> <%= bundle.options.version %>
       * <%= fileHash %>
       */
    cssBuildPath: ./public/css/
    jsBuildPath: ./public/js/
    htmlBuildPath: ./public/

  minify:
    header: |
      /*! Company Name http://www.company-website.com <%= bundle.options.name %>.<%= fileExt %> <%= bundle.options.version %> <%= fileHash %> */
    cssBuildPath: ./public/css/
    jsBuildPath: ./public/js/
    htmlBuildPath: ./public/
    template:
      templatePartial: |
        App.setTemplate('<%= fileBasename %>', '<%= fileContent %>');
      compressWhitespace: true
      templateTypeKeys:
        - mustache
        - handlebars
        - ejs

  jshint:
    jshintrc: ./.jshintrc
    ignoredFiles:
      - jquery.js
      - require.js
      - require-text.js
      - modernizr.js

  # Build Task
  build:

    # This is a global lint flag that is used if there is a lint task specified for a section
    lintBeforeBuild: true

  # Deploy Task
  deploy: ./bundle-wrangler-configs/deploy-config.yaml
