bundlesPath: ./bundle-configs

scriptRenderer: ejs

bundleConfigFormat: yaml

tasks:

  mocha:
    testsDir:
    compile: true

  concat:
    header: |
      /*!
       * Company Name http://www.company-website.com
       * <%= bundle.options.name %>.<%= fileExt %> <%= bundle.options.version %>
       * <%= fileHash %>
       */
    cssBuildPath: ./public/css/
    jsBuildPath: ./public/js/
    htmlBuildPath: ./public/

  minify:
    header: |
      /*! Company Name http://www.company-website.com <%= bundle.options.name %>.<%= fileExt %> <%= bundle.options.version %> <%= fileHash %> */
    cssBuildPath: ./public/css/
    jsBuildPath: ./public/js/
    htmlBuildPath: ./public/
    template:
      templatePartial: |
        App.setTemplate('<%= fileBasename %>', '<%= fileContent %>');
      compressWhitespace: true
      templateTypeKeys:
        - mustache
        - handlebars
        - ejs

  jshint:
    jshintrc: ./.jshintrc
    overwriteDefault: true
    ignoredFiles:
      - jquery.js
      - require.js
      - require-text.js
      - modernizr.js

  # Build Task
  build:

    # This is a global lint flag that is used if there is a lint task specified for a section
    lintBeforeBuild: true

  # Deploy Task
  deploy:

    # Files to be deployed (merged with bundle level definition;  e.g., bundleFile.deploy.files)
    otherFiles: []

    # Global deploy artifacts flag (used if no `deployArtifact` field is found for a section in this config
    deployArtifacts:   true

    # Should files be linted before deploy
    lintBeforeDeploy: false

    domainsToDevelop:

      # Hostname to develop for
      gulpw.elycruz.com:

        # Servers where user can develop for host key (in this case host key is `gulpw.elycruz.com`)
        devHostnames: # slots
          - -devslot1.gulpw-sample.elycruz.com
          - -devslot2.gulpw-sample.elycruz.com
          - -devslot3.gulpw-sample.elycruz.com

        # all sites represent the same website just different instances of the website
        devHostnamePrefixes: # instances
          - web1
          - web2
          - web3

        deployRootFolder: sites/<%= devHostnamePrefix %><%= devHostname %> # web1-devslot1.gulpw-sample.elycruz.com/

        # directories for deploying file types to the website instance chosen
        typesAndDeployPathsMap: # dir
          font: public/media/fonts/
          video: public/media/videos/
          image: public/media/images/
          html: public/
          js: public/js/
          css: public/css/
          md: public/
  csslint:
      csslintrc: ./fe-dev/.csslintrc